parserOptions:
  project: './tsconfig.json'
  tsconfigRootDir: __dirname
extends:
  - standard-with-typescript
  - prettier
ignorePatterns:
  - node_modules
  - dist
rules:
  '@typescript-eslint/consistent-type-definitions':
    - error
    - type
  curly:
    - error
    - all
  no-irregular-whitespace:
    - error
    - skipTemplates: true
      skipStrings: true
  no-console:
    - error
    - allow:
        - info
        - error
        - warn
